### ISSUE TITLE
Previously enrolled users are getting triggered 

### ISSUE THREAD

**Issue by JeremyNichvalodoff** [catalyst/moodle-mod_reengagement#107]
Based on documentation plugin only tracks new enrolments but users enrolled previous to plugin installation are getting notification triggers. Should the documentation on https://moodle.org/plugins/mod_reengagement be updated or is this in fact a bug?

**Comment by danmarsden** [comment]
Yes - this is expected behaviour but the docuementation could be improved. The documentatoin for this plugin is available in the moodledocs here:
https://docs.moodle.org/311/en/Reengagement_activity

the moodle docs site is a public access wiki - feel free to help us by improving the docs and adding troubleshooting information.

If you add a re-engagement plugin to an existing course - yes, all existing users will be handled by the re-engagement plugin based on the rules defined in the re-engagement.

Also - be aware that a lot of further useful information is contained within this discussion:
https://moodle.org/mod/forum/discuss.php?d=337782

thanks,
