### ISSUE TITLE
Second message is never sent.

### ISSUE THREAD

**Issue by Urpokarhu1** [catalyst/moodle-mod_reengagement#66]
Hello

Second message after the first one doesn't seem to work at all. Tested with Moodle 3.5 & mod_reengagement 3.5.2 (2018040501)

Steps to repeat:

1. Check that \mod_reengagement\task\cron_task is run every minute.

2. Add user to a course, check enrolment time f.ex 8:20AM.

3. Create re-engagement -activity with settings:

- Notify user: After delay
- notification delay: 10 minutes
- reminder count: 2
- Activity completion: Reengagement duration 5 minutes

5. First message arrives at 8:35AM (shoudn't it arrive 8:30?)

6. Then another message doesn't arrive at all, when it should arrive at 8:45AM (notification delay 10)

**Comment by Urpokarhu1** [comment]
I first though "Activity completion: Reengagement duration 5 minutes" did affect the sending frequencey but I was wrong, it doesn't matter if you use "Notify user: After delay".

**Comment by Urpokarhu1** [comment]
It seems that "Activity completion: Reengagement duration" affects that no messages are sent after that time has been passed? This must be a bug? This option shoudn't affect when you are using "after time delay" ?

**Comment by danmarsden** [comment]
sounds like expected behaviour to me - the recompletion activity won't send emails if the activity has been flagged as complete.

Unfortunately we don't provide "support" for using our plugins in github - If you have questions about using reengagement, please use the community forums - I see you've already posted here:
https://moodle.org/mod/forum/discuss.php?d=337782#

If you don't get a response there and you are looking for commercial level support then you might consider engaging your local Moodle partner to provide you with support.

Good luck!
