### ISSUE TITLE
Failed to send email 

### ISSUE THREAD

**Issue by sweta484** [catalyst/moodle-mod_reengagement#93]
It is showing Invalid permissions detected when trying to create a directory. Turn debugging on for further details.
But we have checked the moodledata folder permission it is set with 0775 and apache as owner and webadmin1 as group.
Other plugins doesn't have issues in writing the directory.

Kindly help.

Thanks
Sweta

**Comment by danmarsden** [comment]
This doesn't sound like an issue with re-engagment to me... what's the full error output with debugging on and level set to developer?

**Comment by sweta484** [comment]
Hi @danmarsden , 

Thanks for prompt reply but may i know how to debug only cronjob error without having impact on whole side.

Thanks
Sweta

**Comment by danmarsden** [comment]
A Google search (or a hint would be to search for the word "cron" in moodle's config-dist.php) might help you with that - if not, the best place to ask general moodle questions like that are the community forums on moodle.org.

I'm closing this for now because I'm 90% sure this has nothing to do with re-engagement, but feel free to come back and post more info if you think it's still an issue within the re-engagment plugin.

thanks!
